/*
tuya_iot_config.h
Copyright(C),2018-2020, 涂鸦科技 www.tuya.comm
*/

/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by tuya cross-build system.
* It should not be modified by hand.
*/

#ifndef TUYA_IOT_CONFIG_H
#define TUYA_IOT_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

/* default definitons */

#define SYSTEM_SMALL_MEMORY_BEGIN       0       /*small memory systems begin */
#define SYSTEM_REALTEK8710_1M           1
#define SYSTEM_REALTEK8710_2M           2
#define SYSTEM_NON_OS					3		/*no operating system*/
#define SYSTEM_FREERTOS                 98
#define SYSTEM_SMALL_MEMORY_END         99      /*small memory systems end */
#define SYSTEM_LINUX                    100
#define SYSTEM_LITEOS                   120

#define TLS_DISABLE                     0       /* disable tls function */
#define TLS_TUYA_PSK_ONLY               2       /* only enable ciper 0xAE */
#define TLS_TUYA_ECC_PSK                3       /* enable ciper 0xAE && 0xC027 */
#define TLS_TUYA_ECC_ONLY               4       /* only enable ciper 0xC027 */
#define TLS_TUYA_ECC_ONLY_NOSTRIP       5       /* only enable ciper 0xC027, but enable most of mbed-tls configs */
#define TLS_TUYA_ECC_CLIENT_AUTH        6       /* TLS Client Authentication and Server Authentication mode */

#define TUYA_SL_0           0       /* security level 0,Applies to: Resource-constrained devices;Feature: Can only access Tuya Cloud */
#define TUYA_SL_1           1       /* security level 1,Applies to: Resource-constrained devices;Feature: One-way authentication */
#define TUYA_SL_2           2       /* security level 2,Applies to: Resource-rich equipment;Feature: Two-way authentication */
#define TUYA_SL_3           3       /* security level 3,Applies to: Resource-rich equipment;Feature: Two-way authentication,Devices use security chips to protect sensitive information */
#define TUYA_MODIFY_MBEDTLS             1

#define TUYA_OPERATOR_DISABLE           0x0
#define TUYA_OPERATOR_CUCC              0x01
#define TUYA_OPERATOR_CTCC              0x02
#define TUYA_OPERATOR_CMCC              0x04
#define TUYA_OPERATOR_CMCC_ANDLINK      0x08
#define TUYA_OPERATOR_ALL               (TUYA_OPERATOR_CUCC | TUYA_OPERATOR_CTCC | TUYA_OPERATOR_CMCC)


#define TUYA_LAN_V31              0x1
#define TUYA_LAN_V32              0x2
#define TUYA_LAN_V33              0x4
#define TUYA_LAN_V35              0x8
#define TUYA_LAN_ALL              (TUYA_LAN_V31 | TUYA_LAN_V32 | TUYA_LAN_V33 | TUYA_LAN_V35)

#define TUYA_MQ_V21               0x1
#define TUYA_MQ_V22               0x2
#define TUYA_MQ_V23               0x4
#define TUYA_MQ_ALL               (TUYA_MQ_V21 | TUYA_MQ_V22 | TUYA_MQ_V23)

/* custom settings */
#define BUILD_DATE           "2026_07_20"
#define BUILD_TIME           "17_55_32"
#define GIT_USER             "ci_manage"
#define IOT_SDK_VER          "3.14.0"
#define SDK_BETA_VER         "beta.118"
#define TARGET_PLATFORM      "gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf"
#define PROJECT_NAME         "tuyaos-ai"
#define SDK_ID               "tuyaos-ai_3.14.0-beta.118_gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf_RK3506B_0.0.1"
// Generated by Tuya (https://www.tuya.com)
// 基于项目 tuyaos-ai (3.14.0-beta.118)
// 基于工具链 gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf (0.0.1)

//
// SDK
//


//
// TuyaOS TAL Audio SubSystem
//

// CONFIG_ENABLE_AUDIO_SUBSYS is not set


//
// AI Protocol Config
//

// CONFIG_ENABLE_AI_MONITOR is not set

#define AI_MAX_FRAGMENT_LENGTH 8192

// CONFIG_ENABLE_AI_PROTO_DEBUG is not set

#define AI_BIZ_TASK_DELAY 10

#define AI_BIZ_TASK_DELAY_BUSY 1

#define AI_SESSION_MAX_NUM 2

#define AI_BIZ_MAX_NUM 5

#define AI_MAX_ATTR_NUM 10

#define AI_PING_TIMEOUT 6

#define AI_HEARTBEAT_INTERVAL 120

#define AI_PACKET_SECURITY_LEVEL 4

#define AI_CLIENT_STACK_SIZE 4096

#define AI_READ_SOCKET_BUF_SIZE 0

#define AI_WRITE_SOCKET_BUF_SIZE 8192

#define AI_DL_IMAGE_UNIT_SIZE 6144

// CONFIG_AI_HEAP_IN_PSRAM is not set

// CONFIG_AI_STACK_IN_PSRAM is not set

#define AI_SEND_PKT_TIMEOUT 6

#define AI_VERSION 2

#define AI_SUB_VERSION 2

// end of AI Protocol Config


//
// AI Agent Config
//

#define AI_INPUT_STACK_SIZE 4608

#define AI_INPUT_RINGBUF_SIZE 20480

#define AI_INPUT_BUF_SIZE 6144

#define AI_OUTPUT_STACK_SIZE 4096

#define AI_OUTPUT_RINGBUF_SIZE 20480

#define AI_OUTPUT_BUF_SIZE 5120

// end of AI Agent Config


//
// tuya codec configuration
//

#define ENABLE_TUYA_CODEC 1

#define ENABLE_TUYA_CODEC_OPUS 1

// CONFIG_ENABLE_TUYA_CODEC_OPUS_IPC is not set

// CONFIG_ENABLE_TUYA_CODEC_SPEEX is not set

#define ENABLE_BUILD_OPUS 1


//
// System function Config
//

#define ENABLE_LOG 1

#define STACK_SIZE_TIMERQ 4096

// CONFIG_ENABLE_PRINTF_CHECK is not set

// CONFIG_ENABLE_ICC is not set

// end of System function Config


//
// Network config
//

// CONFIG_ENABLE_SET_SOCK_OPT is not set

// CONFIG_ENABLE_MULTI_LINK is not set

// CONFIG_ENABLE_IPv6 is not set

// CONFIG_ENABLE_NETWORK_OPTIONS is not set

// end of Network config


//
// Basic Config
//

#define STACK_SIZE_HEALTH_MONITOR 2048

#define HEALTH_FREE_MEM_THRESHOLD 8192

// CONFIG_ENABLE_OSS_COMPILE_WARNINGS is not set

#define LOCAL_SIGN_DETECT_PERIOD 360


//
// Log Upload Config
//

#define PACKET_SIZE_PER_HTTP_SEND 307200

#define HTTP_SEND_INTERVAL 100

#define PACKET_SIZE_PER_LAN_SEND 8192

#define LAN_SEND_INTERVAL 100

#define MAX_UPD_FILE_SIZE 5242880

// end of Log Upload Config

// end of Basic Config


//
// KV Database Config
//

#define KV_PROTECTED_ENABLE 1

// CONFIG_KV_64BIT_MODE is not set

// CONFIG_ENABLE_KV_FILE is not set

#define ENABLE_KV_PROTECTED 1

// CONFIG_ENABLE_KV_KEY_SEED is not set

// CONFIG_ENABLE_KV_SECURE_CRYPTO is not set

// CONFIG_ENABLE_KV_CACHE is not set

// end of KV Database Config


//
// UF Filesystem Config
//

// CONFIG_ENABLE_UF_FILE is not set

// CONFIG_ENABLE_UF_HUGE_FILE is not set

#define MAX_LENGTH_OF_FILE_FULL_PATH 128

// end of UF Filesystem Config


//
// Event Config
//

#define EVENT_NAME_MAX_LEN 16

// CONFIG_ENABLE_IPC_EVENT is not set

// end of Event Config

#define ENABLE_TUYA_LAN 1

#define TUYA_LAN_VERSION 0x8

#define STACK_SIZE_LAN 4096

#define SBUS_PIPE_CONN_COUNT 10


//
// Firmware OTA config
//

#define OTA_DOWMLOAD_BUF_SIZE 1024

#define STACK_SIZE_UPGRADE 4096

// CONFIG_ENABLE_TUYA_DIFF_OTA is not set

// CONFIG_ENABLE_FIRMWARE_SIGN_TUYA is not set

// CONFIG_ENABLE_FIRMWARE_SIGN_USER is not set

// end of Firmware OTA config


//
// Manufacture Test Config
//

// CONFIG_ENABLE_GPIO_TEST is not set

// CONFIG_ENABLE_PRODUCT_AUTOTEST is not set

// CONFIG_ENABLE_PRODUCT_PLATFORM_TEST is not set

#define STACK_SIZE_MF_TEST 5120

#define MF_TEST_UART_BAUD_RATE 9600

// CONFIG_ENABLE_LOCAL_SIGN is not set

// end of Manufacture Test Config

// CONFIG_ENABLE_LWIP is not set

#define ENABLE_BT_SERVICE 1

#define ENABLE_BT_NETCFG 1

#define ENABLE_BT_ACTIVE 1

#define ENABLE_BT_CTRL 1

#define BT_ADV_INTERVAL_MIN 30

#define BT_ADV_INTERVAL_MAX 60

// CONFIG_ENABLE_BT_OTA is not set

#define BT_REMOTE_CTRL_SCAN_INTERVAL 30

#define BT_REMOTE_CTRL_SCAN_WINDOWS 10

#define ENABLE_BT_TIMER 1

#define ENABLE_BT_MF 1

// CONFIG_ENABLE_MF_BY_BT is not set

// CONFIG_ENABLE_BT_MESH_NODE is not set

// CONFIG_ENABLE_BT_VIRTUAL is not set

#define TUYA_BLE_VER 4

#define ENABLE_TAL_BLUETOOTH 1

#define TAL_BLUETOOTH 1

#define TAL_BLE_SERVICE_VERSION 2

// CONFIG_ENABLE_TUYA_BLE_STACK is not set

#define TY_BT_MOD 1

#define BT_NETCFG 1

#define BT_ACTIVE 1

#define BT_CTRL 1

// CONFIG_BT_REMOTE_CTRL is not set

#define BT_TIMER 1

#define MF_BT 1

// CONFIG_BT_MESH_NODE is not set

// CONFIG_BT_VIRTUAL is not set

#define WIFI_GW 1

// CONFIG_TUYA_HOSTAPD_SUPPORT is not set

#define ENABLE_WIFI_SERVICE 1

#define ENABLE_WIFI_NETCFG 1

// CONFIG_ENABLE_WIFI_EZ is not set

#define ENABLE_WIFI_AP 1

// CONFIG_ENABLE_WIFI_FFS is not set

// CONFIG_ENABLE_WIFI_PEGASUS is not set

// CONFIG_ENABLE_WIFI_PEGASUS_ROUTER is not set

#define ENABLE_WIFI_QRCODE 1

// CONFIG_ENABLE_WIFI_PROTECT is not set

// CONFIG_ENABLE_WIFI_BRIDGE is not set

// CONFIG_ENABLE_WIFI_FFC is not set

// CONFIG_ENABLE_HOSTAPD is not set

#define ENABLE_STATION_AP_MODE 0

#define WIFI_AP_BUF_SIZE 10240

// CONFIG_ENABLE_WIFI_COUNTRY_CODE_V2 is not set

// CONFIG_ENABLE_WIFI_ULTRA_LOWPOWER is not set

// CONFIG_ENABLE_STATIC_IP is not set

// CONFIG_QRCODE_ACTIVE_MODE is not set

#define ENABLE_TUYA_CLOUD 1


//
// Matter Config
//

// CONFIG_ENABLE_MATTER is not set

// CONFIG_ENABLE_LOCAL_LINKAGE is not set

// end of Matter Config

#define ENABLE_ASTRO_TIMER 1

// CONFIG_ENABLE_QRCODE_ACTIVE is not set

#define ENABLE_LOCAL_KEY_UPDATE 1

#define ENABLE_LOGSEQ 1

#define ENABLE_ONLINE_LOG 1


//
// Security Config
//

// CONFIG_ENABLE_BLACK_WHITE_LIST is not set

#define MAX_SECURITY_LEVEL 1

#define TUYA_SECURITY_LEVEL 1

// CONFIG_ENABLE_MBEDTLS_DEBUG is not set

// CONFIG_ENABLE_CUSTOM_CONFIG is not set

// end of Security Config


//
// HTTP Config
//

#define HTTP_MAX_REQ_RESP_HDR_SIZE 1024

#define MAX_HTTP_SESSION_NUM 16

// CONFIG_ENABLE_HTTP_SESSION is not set

#define HTTP_CONNECT_TIMEOUT_MS 5000

// end of HTTP Config


//
// MQTT Config
//

#define TUYA_MQ_VERSION 0x4

#define STACK_SIZE_MQTT_CLIENT 4096

#define QOS1_PUBACK_TIMEOUT 3

#define QOS1_PUBLISH_SLOT_CNT 8

#define QOS1_PUBACK_TIMEOUT_LIMIT 3

#define MAX_RANDOM_DELAY_BEFORE_RECONNECT 300

#define MQTT_HEATBEAT_INTERVAL 60

#define MQTT_HEARTBEAT_RETRY_TIMEOUT 6

#define MQTT_RECV_BUF_SIZE 512

#define MQTT_MAX_MESSGAE_SIZE 4096

#define MQTT_RECV_SELECT_TIMEOUT 3000

// CONFIG_ENABLE_MQTT_QOS1_RESEND is not set

#define MATOP_REQ_TIMEOUT 6

// end of MQTT Config

#define TUYA_IOT_DEBUG 1


//
// System Service Config
//

#define STACK_SIZE_WORK_QUEUE 5120

#define MAX_NODE_NUM_WORK_QUEUE 100

#define STACK_SIZE_MSG_QUEUE 4096

#define MAX_NODE_NUM_MSG_QUEUE 100

#define ENABLE_IOT_DEBUG 1

#define MAX_SIZE_OF_DEBUG_BUF 1024

// CONFIG_ENABLE_LOG_OUTPUT_FORMAT is not set

#define TUYA_REDUCE_BIN 0

// end of System Service Config

#define ENABLE_WEBSOCKET 1

// CONFIG_ENABLE_RTSP_SERVER_LITE is not set


//
// this is ipc core Kconfig
//

#define ENABLE_VIDEO_MSG 1

#define ENABLE_IPC 1

// CONFIG_ENABLE_IPC_4G is not set

// CONFIG_NO_DEFAULT_MEDIA_SRC is not set

#define TUYA_P2P_VIDEO_BUF_MIN_SIZE 448000

#define TUYA_P2P_AUDIO_SEND_BUF_MIN_SIZE 32768

#define TUYA_P2P_AUDIO_RECV_BUF_MIN_SIZE 32768

#define TUYA_P2P_COMMON_BUF_MIN_SIZE 51200


//
// this is tuya cloud operation Kconfig
//

// CONFIG_ENABLE_CLOUD_OPERATION is not set

#define NEW_HTTP_MANAGER 1


//
// this is tuya svc_streaming_p2p Kconfig
//

#define TUYA_P2P 4

// CONFIG_ENABLE_MQTT_P2P is not set

#define STACK_SIZE_P2P_MEDIA_SEND 65536

#define STACK_SIZE_P2P_MEDIA_RECV 65536

#define STACK_SIZE_P2P_CMD_SEND 65536

#define STACK_SIZE_P2P_CMD_RECV 65536

#define STACK_SIZE_P2P_DETECT 65536

#define STACK_SIZE_P2P_LISTEN 131072

#define STACK_SIZE_IPC_UPNP 65536

// CONFIG_ENABLE_TKL_THREAD_CREATE_IN_PSRAM is not set


//
// this is tuya rtp Kconfig
//

#define SUPPORT_RTP 1


//
// this is ring buffer Kconfig
//

#define IPC_CHANNEL_NUM 1


//
// this is two-way video and tuya call Kconfig
//

#define ENABLE_TUYA_CALL 1


//
// this is tmm link config
//

#define ENABLE_TMM_LINK 1

// end of SDK

//
// configure board <your-board-name>
//
#define OPERATING_SYSTEM 100
#define LITTLE_END 1
#define ENABLE_FILE_SYSTEM 1
// CONFIG_ENABLE_WIFI is not set
#define ENABLE_WIRED 1
// CONFIG_ENABLE_BLUETOOTH is not set
// CONFIG_ENABLE_NB is not set
// CONFIG_ENABLE_CELLULAR is not set
// CONFIG_ENABLE_ZIGBEE is not set
// CONFIG_ENABLE_THIRD_NETWORK is not set
// CONFIG_ENABLE_RTC is not set
// CONFIG_ENABLE_WATCHDOG is not set
#define ENABLE_UART 1
#define ENABLE_FLASH 1
#define TUYA_FLASH_TYPE_MAX_PARTITION_NUM 10
// CONFIG_ENABLE_ADC is not set
// CONFIG_ENABLE_PWM is not set
#define ENABLE_GPIO 1
// CONFIG_ENABLE_I2C is not set
// CONFIG_ENABLE_SPI is not set
// CONFIG_ENABLE_TIMER is not set
// CONFIG_ENABLE_DISPLAY is not set
#define ENABLE_MEDIA 1
// CONFIG_ENABLE_PM is not set
// CONFIG_ENABLE_STORAGE is not set
// CONFIG_ENABLE_DAC is not set
// CONFIG_ENABLE_I2S is not set
// CONFIG_ENABLE_WAKEUP is not set
// CONFIG_ENABLE_REGISTER is not set
// CONFIG_ENABLE_PINMUX is not set
// CONFIG_ENABLE_PLATFORM_AES is not set
// CONFIG_ENABLE_PLATFORM_SHA256 is not set
// CONFIG_ENABLE_PLATFORM_MD5 is not set
// CONFIG_ENABLE_PLATFORM_SHA1 is not set
// CONFIG_ENABLE_PLATFORM_RSA is not set
// CONFIG_ENABLE_PLATFORM_ECC is not set
// CONFIG_ENABLE_IPv6 is not set
// end of configure board <your-board-name>
#ifndef TUYA_LAN_VERSION
#define TUYA_LAN_VERSION TUYA_LAN_V35
#endif

#ifndef TUYA_MQ_VERSION
#define TUYA_MQ_VERSION TUYA_MQ_V23
#endif

#ifndef ENABLE_DEVICE_DATA_COLLECT
#define ENABLE_DEVICE_DATA_COLLECT 0
#endif

#ifndef TUYA_WEAK_ATTRIBUTE
#define TUYA_WEAK_ATTRIBUTE __attribute__ ((weak))
#endif

#ifndef KERNEL_VER
#define KERNEL_VER "9.9.9"
#endif

/* custom settings */

#ifdef __cplusplus
}
#endif


#endif
